export const constants = {
    DEFAULT_NUM_OF_PID: 2,
    DEFAULT_NUM_OF_CONCENTRATION: 5,
    DEFAULT_RANGE: 2000,
    DEFAULT_REPEATED_TEST: 4,

    POSSIBLE_NUM_OF_PID: [2],
    POSSIBLE_NUMBER_OF_CONCENTRATION : [5],
    POSSIBLE_RANGE: [20, 200, 2000],
    POSSIBLE_NUM_OF_REPEATED_TEST: [4],

    SELECT_AREA_WIDTH: 150
}